name: Install vcpkg packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows-install:
    runs-on: windows-2019
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.9]  # 3.7, 3.8, 3.9 ]
        architecture: ['x86', 'x64']

    env:
      VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: 'gh-workflows-test'
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: 47d2378c8181ece05ffc51acd2ed60d97e3c9a64
          path: vcpkg
          fetch-depth: 0

      - name: Run vcpkg install
        run: |
          cd %VCPKG_ROOT%
          .\bootstrap-vcpkg.bat
          vcpkg install python3
      
